#
# Copyright (c) 2026 GaraKrral
#
# Source code in this project is licensed under the GNU General Public License v3.0 (GPLv3).
# See the LICENSE file for details.
#
# All game assets, including but not limited to graphics, audio, models, textures,
# and other non-code content, are proprietary and All Rights Reserved unless
# explicitly stated otherwise.
#
#

deps.neoforge=21.1.219

# Minecraft dependency for neoforge.mods.toml
mod.mc_dep=[1.21.1]

# Release title for Modrinth and Curseforge
mod.mc_title=1.21.1

# Space-separated compatible versions for publishing
mod.mc_targets=1.21.1